### ISSUE TITLE
Display Latin Work Titles 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#35] opened 2019-03-01 13:51 UTC
in Perseus, this book is part of Orationes, Cum Senatui gratias egit, Cum populo gratias egit, De domo sua, De haruspicum responso, Pro Sestio, In Vatinium, De provinciis consularibus, Pro Balbo (Latin) (ed. Albert Clark).
I haven't found yet all the different books in Alpheios . at least we should add the latin title of the book
 ORATIO CVM POPVLO GRATIAS EGIT  or just  CVM POPVLO GRATIAS EGIT

in the xml, we have the info in the title tags, one for the English title an done for the latin
<title>To the Citizens after his Return</title>
<title>
Cum Senatui gratias egit, Cum populo gratias egit, De domo sua, De haruspicum responso, Pro Sestio, In Vatinium, De provinciis consularibus, Pro Balbo
</title>

**Comment by monzug** [comment] 2019-03-01 13:57
same for  In the senate after his return  book, the latin title is Cum Senatui gratias egit

**Comment by balmas** [comment] 2019-03-06 13:01
In this case the data is all there, including the latin titles, but we are not displaying the latin work titles in the interface. This is an interface bug therefore.  Updated the title accordingly.

**Comment by balmas** [comment] 2019-05-07 19:39
dupe of #16

**Closed by balmas** 2019-05-07 19:39 UTC
Labels: bug, flask
