### ISSUE TITLE
add alphabetic groups to Authors display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#78] opened 2019-04-16 20:36 UTC
The design for the Authors page calls for the inclusion of Alphabetic groupings on Authors display. This may require Python changes.

https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Collections/Authors.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Collections/Authors.png

**Comment by irina060981** [comment] 2019-05-07 09:11
@balmas, it was very interesting for me to work with this issue, hope, you are not against :)

I have added to flask route similiar structure as for types and created it in the template

**Desktop**
![image](https://user-images.githubusercontent.com/12377640/57287919-d68a4980-70fb-11e9-9345-a4288c9c4584.png)

**Mobile**
![image](https://user-images.githubusercontent.com/12377640/57287952-e2760b80-70fb-11e9-98be-df35d73a0c91.png)

**Comment by irina060981** [comment] 2019-05-07 13:40
Merged and closed

**Comment by balmas** [comment] 2019-05-07 15:01
oops @irina060981 I missed that we also need to sort the alphabetic groups alphabetically....

**Comment by balmas** [comment] 2019-05-07 17:44
also noticed that if you try to scroll to the bottom the page (i.e. to see the copyright button) it jumps you back to the top

**Comment by irina060981** [comment] 2019-05-08 04:31
>also noticed that if you try to scroll to the bottom the page (i.e. to see the copyright button) it jumps you back to the top

I was able to reproduce - it is because of fixed header - will fix.

**Comment by irina060981** [comment] 2019-05-09 02:27
Merged and closed

**Comment by balmas** [comment] 2019-05-09 19:41
ready for testing in beta environment

**Comment by monzug** [comment] 2019-05-10 15:49
sorting is not there yet. tested in 1.0.0.11

**Comment by balmas** [comment] 2019-05-13 12:46
@irina060981 can you take a look at this? Sorting still isn't working. Thanks!

**Comment by irina060981** [comment] 2019-05-13 12:55
@balmas , I am a little confused.
I have updated master branch and start up docker
and authors are sorted:

![image](https://user-images.githubusercontent.com/12377640/57622972-18bafb80-75d2-11e9-84ed-35817b8b17f4.png)

![image](https://user-images.githubusercontent.com/12377640/57622997-28d2db00-75d2-11e9-8b49-665912af58c8.png)

**Comment by irina060981** [comment] 2019-05-13 12:56
I have compared to http://texts-beta.alpheios.net/
the authors are the same but not sorted

could you tell me what should I do to reprduce the bug?

**Comment by balmas** [comment] 2019-05-13 13:04
hmm. that's really strange.I don't know why it would behave differently. will investigate.

**Comment by balmas** [comment] 2019-05-13 13:11
the question for me is actually why it appears sorted in the Docker environment. Because I think the problem is that you are using a dict for the sortedLetters and the key order isn't fixed. 

You either need an array to hold the sorted keys or else sort in the template before printing.

i.e. this code in __init__.py:

```
for key in sorted(letters.keys()) :
                lettersSorted[key] = letters[key]
```

is updating each key in the lettersSorted dict in alphabetic order, but the lettersSorted dict doesn't retain that sorting

**Comment by irina060981** [comment] 2019-05-14 09:25
Interesting, I thought that dicts in python save the order of insertions
(I used this discussion to think so)
and as I create a new dict `lettersSorted` and insert items there in alphabetical order - it should save this order.
But this feature are from Python 3.6 (it is used in docker container), so I have my authors correctly ordered.
But it seems to me that production environment could have a less version. And before 3.6 dictionary has not any order.
I think that it is the reason of the following difference in result.

**Comment by irina060981** [comment] 2019-05-14 09:31
I have changed dict to orderedDict - to be undepended on the version - in my environment it works well.
Hope it will work in production!
![image](https://user-images.githubusercontent.com/12377640/57687461-d13e7900-767e-11e9-8808-d6c2d7e61af1.png)

**Comment by irina060981** [comment] 2019-05-14 12:17
merged and closed

**Closed by irina060981** 2019-05-14 12:17 UTC
Labels: css/js/html, design, flask, waiting_merge
