### ISSUE TITLE
difficulty with notes on iPhone xr

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#221] opened 2019-07-17 12:13 UTC
notes are displayed now. however on iPhone xr they are not easy to select. if I enlarge the text, most of the time it does capture the word next to it rather than the note.

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/4#issuecomment-511904551_

**Comment by balmas** [comment] 2019-07-30 13:39
I don't know what to do about this.   @irina060981 do you have ideas for how better to represent the notes for the mobile display?  (the are little [*] with a popover e.g. see the first paragraph of Cicero Academica)

**Comment by irina060981** [comment] 2019-07-31 01:11
Also here it is a small css bug - wil fix too
![image](https://user-images.githubusercontent.com/12377640/62176227-0015e280-b384-11e9-966e-b42bc28f52f9.png)

**Comment by irina060981** [comment] 2019-07-31 01:21
> I don't know what to do about this. @irina060981 do you have ideas for how better to represent the notes for the mobile display? (the are little [*] with a popover e.g. see the first paragraph of Cicero Academica)

I couldn't reproduce exactly, on my Iphone it is really easy to open popover - I simply tap in the place and that's all - it is working well.
But I have problems with opening big popup - for example this one
```
esse scribere quod occultari velit;[*]
```

it opens and closes at once

I see only the following variants:
 -- for the clicking - I could only suggest to increase the area of `span[data-toggle="popover"]`
 -- for the showing big popup - We could restyle it to the simply a block under the popup with the width = 90% of the screen and real height

@monzug and @balmas , what do you think?

**Comment by balmas** [comment] 2019-07-31 12:04
these seem like reasonable suggestions to me

**Comment by irina060981** [comment] 2019-08-05 11:54
Merged and closed

**Closed by irina060981** 2019-08-05 11:54 UTC
Labels: bug, mobile

**Comment by monzug** [comment] 2019-08-05 15:29
beautiful. Thanks!

**Comment by monzug** [comment] 2019-08-05 15:36
@irina060981  what was the small css bug? is it the alignment of author and sub section?

**Comment by irina060981** [comment] 2019-08-05 21:27
> @irina060981 what was the small css bug? is it the alignment of author and sub section?

No, I didn't touch the author in a subsection. 
I only made an [*] - bigger and placed popover at the bottom (not to the right) - and that's all.
Is there any problem with aligning author and subsection?

**Comment by monzug** [comment] 2019-08-06 13:21
Though you wanted to align cicero (author) and Philosophia (subsection). Just curious. all good here
