### ISSUE TITLE
Find passage in Carmina, Catullus

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#232] opened 2019-07-24 16:09 UTC
Jumping from one section of Carmina to an other using the Find passage feature in Carmina, Callustus  e.g. https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/1?subreference=1, somehow we do not display the section breakers
tested in FF and Chrome
see screenshot
![catullus](https://user-images.githubusercontent.com/41396793/61808428-5b3a5900-ae09-11e9-992c-36acae485d2c.JPG)

**Comment by balmas** [comment] 2019-07-24 16:52
this is essentially the same problem as #193 
When you jump to the poem level, vs poem/line the code to display the poem identifiers isn't getting triggered.

A separate issue here is that the meter milestones are displaying because they are not getting filtered out. I think we should hide them. Will make a new issue for that.

**Comment by monzug** [comment] 2019-07-24 17:04
uhm, in this case the section breaker is displayed all the times, except when jumping to it using the passage feature

**Comment by balmas** [comment] 2019-07-24 18:10
What I want to hide is the word "Phalaecean" which is the meter milestone

The section breaks only aren't there if you jump to the poem level (e.g. 1)

If you jump to the poem/line, you should see them (e.g. 1.1)

**Comment by monzug** [comment] 2019-07-24 18:13
ah, ok. thanks

**Comment by balmas** [comment] 2019-08-08 18:58
closing this one as dupe of #193

**Closed by balmas** 2019-08-08 18:58 UTC
Labels: bug, data issue, duplicate
