### ISSUE TITLE
style dropdown menu

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#76] opened 2019-04-16 19:59 UTC
Style of the dropdown menu in the mainnav should look as follows

Desktop: 
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Main-Menu-Open.png

Mobile
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/PWA-Main-Menu-Logged-Out.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/PWA-Main-Menu-Logged-In.png

HTML Template: 
https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/navmenu.html
https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/login.html
https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/logout.html

**Comment by irina060981** [comment] 2019-04-25 11:38
@balmas, I have several questions here:

1) label in design
![image](https://user-images.githubusercontent.com/12377640/56732480-d6f01f80-67a0-11e9-8d35-0af06ddc7555.png)

We have label in design - **Collections**, but now in menu we don't have it
![image](https://user-images.githubusercontent.com/12377640/56732514-fc7d2900-67a0-11e9-8e1e-53b250de9517.png)

How could I add it?

2) in the code we have condition for showing current item, but there is no current in fact.
how should be shown the current?

3) in design we have very different design for dropdown for mobile and desktop.
For desktop - it is a dropdown sticked to the left border and to the bottom of navbar:
![image](https://user-images.githubusercontent.com/12377640/56732843-dc019e80-67a1-11e9-8461-2a0f35737bf0.png)

For mobile - it is a modal popup, with shadowed backdrop and sticked to the top left corner and has 100% height and 95% width
Also it has close button on the right (on desktop - on the left):
![image](https://user-images.githubusercontent.com/12377640/56732869-e7ed6080-67a1-11e9-9ad3-8f168ff6dfc9.png)

Am I right? Should I implement this two different ways to show dropdown?

**Comment by balmas** [comment] 2019-04-25 11:49
About the collections label -- I missed that. I think you could just add it as a static text -- we only show collections items in the menu, never text/browse, so it doesn't need to change per page

**Comment by balmas** [comment] 2019-04-25 11:54
>in the code we have condition for showing current item, but there is no current in fact.
how should be shown the current?

I think that's just a carry over from when this code was used to create a breadcrumb. I don't think we will ever show the current item in the menu so you could get rid of that test I think.

**Comment by balmas** [comment] 2019-04-25 11:57
>In design we have very different design for dropdown for mobile and desktop.
Yes, the design firm had suggested two slightly different approaches to the menu. On the desktop, they wanted it to slide out from the left, with the icons aligned under the menu icon, so that the user could just bring their mouse right down to the item.  I don't know how hard that is to implement though.   If it's a lot of work I am open to other suggestions.

**Comment by irina060981** [comment] 2019-04-25 12:10
@balmas , thank you for all answers!

>In design we have very different design for dropdown for mobile and desktop.

There is no such standard components for such behaviour.
and it is rather a dificult approach to make such a different js behaviour based on css media queries.

But I will think about it tomorrow - how could I realize it :)

From my own point of view - it is worth to select one variant of handling with menu - side menu is a good variant - for example like this behaviour:
https://bootstrapious.com/p/bootstrap-sidebar#3-fixed-scrollable-sidebar-menu-with-a-content-overlay
I think it is the same as mobile design.

And we could add headers to the menu - to make it the same from the top, as it is under navbar.
What do you think?

**Comment by balmas** [comment] 2019-04-25 12:29
I would be fine with you trying that to see how it works. The main priority for the reading environment is the mobile UI, so I'm okay with optimizing for that.

**Comment by irina060981** [comment] 2019-04-26 06:05
I mean this:
**for desktop**
![image](https://user-images.githubusercontent.com/12377640/56786628-fe94c580-683c-11e9-8cad-88edbbdec45b.png)

the place of menu-button and close menu button are on the same place - you should not move the mouse

and the same for mobile
![image](https://user-images.githubusercontent.com/12377640/56786662-1ec48480-683d-11e9-89a2-17390763b460.png)

**Comment by irina060981** [comment] 2019-04-26 06:21
@balmas, there is no mail in the profile
![image](https://user-images.githubusercontent.com/12377640/56787262-516f7c80-683f-11e9-8430-28b94f084fe2.png)

But by design I should place it. May it needs to be fixed in flask?

**Comment by balmas** [comment] 2019-04-26 16:45
I am not sure if we want to include the email address as it is in the design mockup.  I am not really in favor of showing email addresses on screen.  I think we'll stick with nickname for now.

**Comment by irina060981** [comment] 2019-04-26 23:39
Merged and closed

**Comment by balmas** [comment] 2019-04-30 13:45
live in texts-test (embed-lib 1.0.0.6)

**Comment by monzug** [comment] 2019-04-30 19:56
I prefer to show only the username too. 
I am confused on how the drop-down menu is populated.  if I follow the links from main menu, first I click on Language, then I select a language. at this point  in the top nav I have Language/Authors but in main menu I still have only Language. if I select an author, then top nav is language/authors/works and main menu is Language/Authors. when I select a work, then main menu has Language/Authors/Works.
Note that each link from main menu (either Language or Authors or Works) takes to the correct page. Is this nav in main menu by design?

**Comment by balmas** [comment] 2019-05-01 11:47
the menu is basically a different representation of the breadcrumb. 

>If I follow the links from main menu, first I click on Language, then I select a language. at this point in the top nav I have Language/Authors but in main menu I still have only Language.

In the top nav, Authors is the current page, so not clickable. And so forth.

It is inconsistent though that when you are are the first page, languages, you still have that clickable in the menu. That's due to the way the app is designed to have a first page that is not any of those, but I could probably fix that if you think it's too confusing.

**Comment by monzug** [comment] 2019-05-01 11:56
let me think about. there is nothing wrong here so this is super low priority. I think it's confusing when you navigate from main menu to top nav and back to main menu.

**Comment by monzug** [comment] 2019-05-01 12:03
forgot to mention that I do not see "Logged in as username". we agree on not showing the email address but I thought we still wanted the logged in/out info.

**Comment by balmas** [comment] 2019-05-01 12:05
yes, that should be there. giving back to @irina060981 to investigate.

**Comment by irina060981** [comment] 2019-05-01 12:21
We are showing logged in only in mobile left slide menu.
On desktop - it is absent in menu.
This way:
![image](https://user-images.githubusercontent.com/12377640/57016783-66914480-6c5f-11e9-897c-1410fe12c7c5.png)

(here it is a small css error for logged in - I have fixed it in the todays PR)

![image](https://user-images.githubusercontent.com/12377640/57016813-7dd03200-6c5f-11e9-864f-823ec2aa8acd.png)

screens are from the current
http://texts-test.alpheios.net/

**Comment by irina060981** [comment] 2019-05-01 12:23
And we show logged in when menu is fixed on desktop
![image](https://user-images.githubusercontent.com/12377640/57016864-b4a64800-6c5f-11e9-9582-a4c55bdc5fed.png)

**Comment by monzug** [comment] 2019-05-01 12:31
yes, I can see it now - see screenshot

**Comment by monzug** [comment] 2019-05-01 12:31
Irina, can you explain what's the fixed main menu?

**Comment by irina060981** [comment] 2019-05-01 12:35
> Irina, can you explain what's the fixed main menu?
It is from this issue
https://github.com/alpheios-project/alpheios_nemo_ui/issues/85

when you scroll some long page (for testing I simply make the window to have a small height manually)
a part of the navbar becomes fixed - will make a small video for you

**Comment by irina060981** [comment] 2019-05-01 12:38
https://www.dropbox.com/s/0d8ubsh5szbgfv3/testFixedNav.wmv?dl=0

**Comment by monzug** [comment] 2019-05-01 12:39
I haven't looked at it yet. uhm, no video needed but will test the issue
asap.

**Comment by monzug** [comment] 2019-05-01 12:40
Thanks!

**Comment by irina060981** [comment] 2019-05-01 12:41
I have a nice easy video maker from the desktop and it is really easy for me to make video to show something for testing or explaining. I like it :)

**Comment by monzug** [comment] 2019-05-01 12:53
very handy, indeed. Thanks

**Comment by monzug** [comment] 2019-05-01 15:04
from #85, it looks like we plan to have the "login/logout additionally in
the dropdown menu"  for desktop - so, what's the last word on this?
1) login/logout only visible for the fixed state
or
2) login/logout always visible in main menu for desktop
Thanks

**Comment by balmas** [comment] 2019-05-01 19:03
@monzug I am ambivalent about this. Do you think it should always be in the menu for consistency even when it's in the header on desktop?

**Comment by monzug** [comment] 2019-05-01 19:16
nope, but we need to make a final decision. I am always pro easy and simple solution (in this case it would be login/logout always visible). As we have implemented the approach to be visible for the fixed state, I am fine to go with it. are you?

**Comment by balmas** [comment] 2019-05-01 19:22
yes, I'm fine with it the way it is for now.

**Comment by irina060981** [comment] 2019-05-02 06:09
Then could we close the issue? Or I should do some changes?

**Comment by monzug** [comment] 2019-05-02 06:17
re-assign back to me as I have to evaluate the navigation from main menu vs top nav.

**Comment by monzug** [comment] 2019-05-14 12:57
I think it's ok, we always have the login state on the top nav.

**Closed by monzug** 2019-05-14 12:58 UTC
Labels: css/js/html, design
